### ISSUE TITLE
Presenters Tests

### ISSUE THREAD

**Issue by jjvargas** [OpenConference/OpenConference-android#27]
Can you somehow use the MvpLcePresenterTest  class you were using in other projects to test the presenters ? 

Or is there any new magic way to do it in Kotlin ?

**Comment by sockeqwe** [comment]
Since I don't use `MvpLceView` in this project, but rather my own [LceView implementetation](https://github.com/OpenConference/OpenConference-android/blob/master/app/src/main/java/com/openconference/util/lce/LceView.kt), `MvpLcePresenterTest` doesn't work with that one out of the box.

The main reason why not to use `MvpLceView` but build a own `LceView` is that there is no pull-to-refresh in the app and also `showError()` and `showContent()` are slightly different.

No Kotlin magic.
